# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('eingangswert', models.IntegerField(default=0)),
                ('ausgangswert', models.IntegerField(default=0)),
                ('mensch', models.CharField(blank=True, choices=[('E', 'Zutritt'), ('L', 'Ausgang'), ('O', 'sonstig')], max_length=1)),
                ('computer', models.CharField(blank=True, choices=[('E', 'Zutritt'), ('L', 'Ausgang'), ('O', 'sonstig')], max_length=1)),
                ('event', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
    ]
